# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    paths:
      - 'source_project/**'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        mkdir -p ~/.metagpt && printf "llm:\n  api_type: \"openai\"\n  model: \"gpt-3.5-turbo-1106\"\n  base_url: \"https://api.openai.com/v1\"\n  api_key: \"your key\"" > ~/.metagpt/config2.yaml && cat ~/.metagpt/config2.yaml
        git diff HEAD~1 HEAD > diff.txt
    - name: Run CICD
      run: |
        python main.py
